apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-db
          image: gcr.io/crypto-handbook-348422/redis
          ports:
            - containerPort: 6379